
  //表情名称
  var emojiNames = ['aixin','hecai','woshou','baoquan','qiang','quantou','fendou','guzhang','hanxiao','ciya',
    'dabing','daku','touxiao','tiaopi','weixiao','yiwen','deyi','haixiu','baobao','dangao',
    'meigui','qidao','shengli','aiqing','denglong','dengpao','dashuai','aini','aoman','baiyan',
    'bangbangtang','baojing','bianbian','bianpao','biezui','bishi','bizui','cahan','caidao','caiqiu',
    'chajing','chaopiao','chexiang','dao','dashan','diaoxie','duoyun','facai','fadai','fadou',
    'fakuang','fan','fanu','feiji','feiwen','fengche','ganga','gouwu','gouying','haqian',
    'henai','huaixiao','huishou','huitou','jidong','jie','jiewu','jingkong','jingya','kafei',
    'kaiche','keai','kelian','ketou','kge','koubi','ku','kuaikule','kulou','kun',
    'lanqiu','lenghan','liuhan','liulei','liwu','nanguo','naozhong','no','ok','ouhuo',
    'pijiu','pingpang','qiaoda','qingwa','qinqin','qiudale','ruo','se','shafa','shandian',
    'shiai','shouqiang','shuai','shuangxi','shui','taiyang','tiaosheng','tiaotiao','tu','weiqu',
    'xia','xiamian','xiangjiao','xianwen','xiayu','xigua','xinsui','xiongmao','xu','yao',
    'yingxian','zuochetou','youchexiang','zuohengheng','youhengheng','youjian','zuotaiji','youtaiji','yueliang','yun',
    'zaijian','zhadan','zhijing','zhuakuang','zhuanjie','zhuanquan','zhuqiu','zhutou','zouma','pachong'
  ];

 
  //'./img/face/emotion_aini.png',
  var face = [
    './img/face/emotion_aini.png',
    './img/face/emotion_aiqing.png',
    './img/face/emotion_aixin.png',
    './img/face/emotion_aoman.png',
    './img/face/emotion_baiyan.png',
    './img/face/emotion_bangbangtang.png',
    './img/face/emotion_baobao.png',
    './img/face/emotion_baojing.png',
    './img/face/emotion_baoquan.png',
    './img/face/emotion_bianbian.png',
    './img/face/emotion_bianpao.png',
    './img/face/emotion_biezui.png',
    './img/face/emotion_bishi.png',
    './img/face/emotion_bizui.png',
    './img/face/emotion_cahan.png',
    './img/face/emotion_caidao.png',
    './img/face/emotion_caiqiu.png',
    './img/face/emotion_chajing.png',
    './img/face/emotion_chaopiao.png',
    './img/face/emotion_chexiang.png',
    './img/face/emotion_ciya.png',
    './img/face/emotion_dabing.png',
    './img/face/emotion_daku.png',
    './img/face/emotion_dangao.png',
    './img/face/emotion_dao.png',
    './img/face/emotion_dashan.png',
    './img/face/emotion_dashuai.png',
    './img/face/emotion_denglong.png',
    './img/face/emotion_dengpao.png',
    './img/face/emotion_deyi.png',
    './img/face/emotion_diaoxie.png',
    './img/face/emotion_duoyun.png',
    './img/face/emotion_facai.png',
    './img/face/emotion_fadai.png',
    './img/face/emotion_fadou.png',
    './img/face/emotion_fakuang.png',
    './img/face/emotion_fan.png',
    './img/face/emotion_fanu.png',
    './img/face/emotion_feiji.png',
    './img/face/emotion_feiwen.png',
    './img/face/emotion_fendou.png',
    './img/face/emotion_fengche.png',
    './img/face/emotion_ganga.png',
    './img/face/emotion_gouwu.png',
    './img/face/emotion_gouying.png',
    './img/face/emotion_guzhang.png',
    './img/face/emotion_haixiu.png',
    './img/face/emotion_hanxiao.png',
    './img/face/emotion_haqian.png',
    './img/face/emotion_hecai.png',
    './img/face/emotion_henai.png',
    './img/face/emotion_huaixiao.png',
    './img/face/emotion_huishou.png',
    './img/face/emotion_huitou.png',
    './img/face/emotion_jidong.png',
    './img/face/emotion_jie.png',
    './img/face/emotion_jiewu.png',
    './img/face/emotion_jingkong.png',
    './img/face/emotion_jingya.png',
    './img/face/emotion_kafei.png',
    './img/face/emotion_kaiche.png',
    './img/face/emotion_keai.png',
    './img/face/emotion_kelian.png',
    './img/face/emotion_ketou.png',
    './img/face/emotion_kge.png',
    './img/face/emotion_koubi.png',
    './img/face/emotion_ku.png',
    './img/face/emotion_kuaikule.png',
    './img/face/emotion_kulou.png',
    './img/face/emotion_kun.png',
    './img/face/emotion_lanqiu.png',
    './img/face/emotion_lenghan.png',
    './img/face/emotion_liuhan.png',
    './img/face/emotion_liulei.png',
    './img/face/emotion_liwu.png',
    './img/face/emotion_meigui.png',
    './img/face/emotion_nanguo.png',
    './img/face/emotion_naozhong.png',
    './img/face/emotion_no.png',
    './img/face/emotion_ok.png',
    './img/face/emotion_ouhuo.png',
    './img/face/emotion_pachong.png',
    './img/face/emotion_pijiu.png',
    './img/face/emotion_pingpang.png',
    './img/face/emotion_qiang.png',
    './img/face/emotion_qiaoda.png',
    './img/face/emotion_qidao.png',
    './img/face/emotion_qingwa.png',
    './img/face/emotion_qinqin.png',
    './img/face/emotion_qiudale.png',
    './img/face/emotion_quantou.png',
    './img/face/emotion_ruo.png',
    './img/face/emotion_se.png',
    './img/face/emotion_shafa.png',
    './img/face/emotion_shandian.png',
    './img/face/emotion_shengli.png',
    './img/face/emotion_shiai.png',
    './img/face/emotion_shouqiang.png',
    './img/face/emotion_shuai.png',
    './img/face/emotion_shuangxi.png',
    './img/face/emotion_shui.png',
    './img/face/emotion_taiyang.png',
    './img/face/emotion_tiaopi.png',
    './img/face/emotion_tiaosheng.png',
    './img/face/emotion_tiaotiao.png',
    './img/face/emotion_touxiao.png',
    './img/face/emotion_tu.png',
    './img/face/emotion_weiqu.png',
    './img/face/emotion_weixiao.png',
    './img/face/emotion_woshou.png',
    './img/face/emotion_xia.png',
    './img/face/emotion_xiamian.png',
    './img/face/emotion_xiangjiao.png',
    './img/face/emotion_xianwen.png',
    './img/face/emotion_xiayu.png',
    './img/face/emotion_xigua.png',
    './img/face/emotion_xinsui.png',
    './img/face/emotion_xiongmao.png',
    './img/face/emotion_xu.png',
    './img/face/emotion_yao.png',
    './img/face/emotion_yingxian.png',
    './img/face/emotion_yiwen.png',
    './img/face/emotion_youchexiang.png',
    './img/face/emotion_youhengheng.png',
    './img/face/emotion_youjian.png',
    './img/face/emotion_youtaiji.png',
    './img/face/emotion_yueliang.png',
    './img/face/emotion_yun.png',
    './img/face/emotion_zaijian.png',
    './img/face/emotion_zhadan.png',
    './img/face/emotion_zhijing.png',
    './img/face/emotion_zhuakuang.png',
    './img/face/emotion_zhuanjie.png',
    './img/face/emotion_zhuanquan.png',
    './img/face/emotion_zhuqiu.png',
    './img/face/emotion_zhutou.png',
    './img/face/emotion_zouma.png',
    './img/face/emotion_zuochetou.png',
    './img/face/emotion_zuohengheng.png',
    './img/face/emotion_zuotaiji.png'
 ];

var result = [];

emojiNames.forEach((item, index) => {

  face.forEach((item1, index1) => {
    var name = item1.replace('./img/face/emotion_', '').replace('.png', '');
    // var i = emojiNames.indexOf(name);
    if (name === item) {
      result.push(`[em:${index1}]`);

    }

    // if (index === -1) {
    //   console.log('error', name);
    // }
  })
})

var a = '马秦测试[em:2][em:4][em:4][em:6][em:15][em:15]';
var b = Face().getAndDealStr(a);